export default {
  isLoading: false,
  about: {
    companyName: "",
    about_companySector: "",
    about_targetAudience: "",
    marketingObjectives: "",
    additionalInfo: "",
    raceMesages: [""],
  },
  plan: {
    planning: {
      intDigiPlan: false,
      markStrat: false,
      digiTransPlan: false,
      empSkillsGap: false,
      empDevPlans: false,
      aiMartechStack: false,
      strategicInitiativesAndActions: [""],
    },
    goals: {
      smartObj: false,
      gaCustom: false,
      digPerfDash: false,
      strategicInitiativesAndActions: [""],
    },
    media: {
      digMediaEff: false,
      sopMedia: false,
      strategicInitiativesAndActions: [""],
    },
    content: {
      contMarkEff: false,
      contMarkStrat: false,
      genAiUse: false,
      strategicInitiativesAndActions: [""],
    },
    experience: {
      webUsability: false,
      structTesting: false,
      croPlan: false,
      strategicInitiativesAndActions: [""],
    },
    conversational: {
      emailContactPlan: false,
      custRetention: false,
      strategicInitiativesAndActions: [""],
    },
  },
  reach: {
    planning: {
      acqBudget: false,
      brandMsg: false,
      keywordRes: false,
      strategicInitiativesAndActions: [""],
    },
    goals: {
      convForecast: false,
      keyphraseGap: false,
      gA4Events: false,
      strategicInitiativesAndActions: [""],
    },
    media: {
      searchStrategy: false,
      paidMediaProspect: false,
      influencerMarket: false,
      strategicInitiativesAndActions: [""],
    },
    content: {
      tofuContent: false,
      seoInbound: false,
      strategicInitiativesAndActions: [""],
    },
    experience: {
      techSEO: false,
      webSpeedMobile: false,
      strategicInitiativesAndActions: [""],
    },
    conversational: {
      emailCampaigns: false,
      coMarketingEmail: false,
      socialSelling: false,
      strategicInitiativesAndActions: [""],
    },
  },
  act: {
    planning: {
      defContStrat: false,
      contentPersona: false,
      aiGovernance: false,
      strategicInitiativesAndActions: [""],
    },
    goals: {
      convRateMeas: false,
      visitorQuality: false,
      strategicInitiativesAndActions: [""],
    },
    media: {
      interactionReview: false,
      adRetargeting: false,
      strategicInitiativesAndActions: [""],
    },
    content: {
      mofuOpt: false,
      genAiUse: false,
      strategicInitiativesAndActions: [""],
    },
    experience: {
      landingPageOpt: false,
      leadProfiling: false,
      strategicInitiativesAndActions: [""],
    },
    conversational: {
      welcomeEmails: false,
      communityInteraction: false,
      strategicInitiativesAndActions: [""],
    },
  },
  convert: {
    planning: {
      structTestPlan: false,
      croPlan: false,
      regularTesting: false,
      strategicInitiativesAndActions: [""],
    },
    goals: {
      ecommTrack: false,
      attribution: false,
      offlineInfluence: false,
      strategicInitiativesAndActions: [""],
    },
    media: { googleAdsInvest: false, strategicInitiativesAndActions: [""] },
    content: {
      bofuContent: false,
      structTestCRO: false,
      strategicInitiativesAndActions: [""],
    },
    experience: {
      basketCheckoutEff: false,
      multichannelConv: false,
      personalizationEff: false,
      strategicInitiativesAndActions: [""],
    },
    conversational: {
      emailNurture: false,
      sitePersonalization: false,
      digitalSalesAssist: false,
      strategicInitiativesAndActions: [""],
    },
  },
  engage: {
    planning: {
      custResearch: false,
      emailPlan: false,
      strategicInitiativesAndActions: [""],
    },
    goals: {
      customDims: false,
      engagementTrack: false,
      custProfile: false,
      custSatisfaction: false,
      strategicInitiativesAndActions: [""],
    },
    media: {
      custListsReview: false,
      googleAdsOpt: false,
      orgSocialAmplify: false,
      strategicInitiativesAndActions: [""],
    },
    content: {
      rofuRetention: false,
      returnVisitPers: false,
      supportContent: false,
      strategicInitiativesAndActions: [""],
    },
    experience: {
      onBoarding: false,
      custJourney: false,
      loyaltyDrivers: false,
      strategicInitiativesAndActions: [""],
    },
    conversational: {
      onBoardingRev: false,
      newsletters: false,
      emailComm: false,
      commPref: false,
      socialCommunities: false,
      strategicInitiativesAndActions: [""],
    },
  },
};
